services:
  backend:
    build:
      context: ./src/backend
    ports:
      - "8080:8080"
    networks:
      - appnet
    restart:
      unless-stopped

  frontend:
    build:
      context: ./src/frontend
    ports:
      - "3000:3000"
    networks:
      - appnet
    restart:
      unless-stopped

networks:
  appnet:
